### ISSUE TITLE
Could not autowire. There is more than one bean of 'HazelcastInstance' type.

### ISSUE THREAD

**Issue by isfong** [ralscha/blog2019#13]
IntelliJ IDEA tips [Application#L23-L24](https://github.com/ralscha/blog2019/blob/master/ratelimit/src/main/java/ch/rasc/ratelimit/Application.java#L23-L24)
Could not autowire. There is more than one bean of 'HazelcastInstance' type.
Beans:
hazelcastInstance   (HazelcastServerConfiguration.class) hazelcastInstance   (HazelcastClientConfiguration.class)

**Comment by ralscha** [comment]
Can't reproduce.

This is what I did

```
git clone https://github.com/ralscha/blog2019.git
cd blog2019/ratelimit
./mvnw spring-boot:run
```

**Comment by isfong** [comment]
> 

Yes, it does not affect service startup, it is just a canonical check for Jetbrains on Spring Bean assembly.  
I use getOrCreateHazelcastInstance avoid this problem, perhaps it was hazelcast-spring's faults Or maybe it doesn't matter. 
```java
    @Bean
    HazelcastInstance clusterHazelcastInstance( ) {
        Config config = new Config( );
        config.setInstanceName( "cluster.local.hz" );
        config.getCPSubsystemConfig( ).setCPMemberCount( 3 );
        return Hazelcast.getOrCreateHazelcastInstance( config );
    }
```

**Comment by ralscha** [comment]
I see. Thanks for the feedback.
