### ISSUE TITLE
non-compliant form encoding

### ISSUE THREAD

**Issue by robaho** [ralscha/blog2019#18]
Just an FYI, the code here https://github.com/ralscha/blog2019/blob/master/java11httpclient/client/src/main/java/ch/rasc/httpclient/File.java#L69-L91

is not compliant with the RFC. From the RFC:

>The boundary delimiter MUST occur at the beginning of a line, i.e., following a CRLF, and the initial CRLF is considered to be attached to the boundary delimiter line rather than part of the preceding part. The boundary may be followed by zero or more characters of linear whitespace.

The code adds a CRLF at the end of the file, so the 'part end' becomes compliant.

It should be adding a CRLF as part of the first boundary, otherwise the data stream looks like:

```
headerCRLF
header...CRLF
--boundary...
```

when it should be

```
headerCRLF
header...CRLF
CRLF--boundary...
```

I think most parsers will deal with this regardless, but I felt it should be noted.

**Comment by ralscha** [comment]
Is this correct?

https://github.com/ralscha/blog2019/commit/512f648a55237d2c0aff70d33d2879d63ce4aa1d

**Comment by robaho** [comment]
That will fix it afaict. 

I think you could reorganize the code to add it to the separator and stop adding it after the file bytes for additional clarity on what is happening but it isn’t strictly necessary.
