### ISSUE TITLE
This implementation is  __INSECURE__.

### ISSUE THREAD

**Issue by rzwitserloot** [ralscha/blog2019#5]
Let's say I know a user account's password, or I guessed it, but I do not have their TOTP device. That is precisely the scenario TOTP is supposed to protect against.

And yet 6 hours later, I'm in their account. For sure. Guaranteed. If it's a nice server or it's hosting in a virtual park where I can trivially colocate right next to it in the network, maybe as little as half an hour. How?

I just keep guessing codes. Hey, any given time, 5 TOTP codes are valid, and there are only a million codes, so, any time I guess, I have a 1 in 200,000 shot of getting lucky. Assuming I can make a request every 100msec (and that's being 'generous'; usually I can go much faster; TOTP checking is not intentionally speed limited the way things like bcrypt are), I can fire off about 200k requests, giving me very reasonable odds I hit the jackpot in one of those, in less than 6 hours.

The only secure way to do TOTP is to __persistently__ remember that a given user entered an invalid TOTP code: Have a boolean flag in the database.

After a single miss, that user is now in 'TOTP additional security' mode. In this mode, the user must enter 3 consecutive codes from their device. Yes, annoying, but by triggering after even a single failed attempt, you also prevent against scheduled attacks (if I know you log in in the morning and also log in after lunch, and you give the user 10 chances, resetting these shots after a successful TOTP code, then I can still try 20 codes a day without the user ever figuring it out).

3 codes give you such good assurances they really do have a device with the original secret key, that you can be quite generous: Check every code up to 13 to 24 hours ahead and behind (that's around 5000 codes; no, the odds of randomly guessing right are astronomical and not worth taking seriously. a million-million-million is a very large divider, fortunately), and tell the user if their clock is off as a service while you're at it.

This is not a denial-of-service attack: TOTP checking isn't done unless the user knows their password. A hacker that knows the user's password and is now guessing TOTP? That's not denial of service. That is an active security case. It is entirely justified to inconvenience the user. Good, even. Let em know if they don't recall messing up a TOTP scan that their password may be compromised.

**Comment by ralscha** [comment]
Thanks for the feedback. I like this idea. How would you implement that in the GUI? 

What do you think about adding an account lock feature that locks the account after x number of invalid login tries (wrong password, wrong totp)?

**Comment by rzwitserloot** [comment]
You cannot 'unify' the notion of a failed login. Context is important:

* Your average decent password has ~40 bits of entropy. TOTP has 17.5. Stopping attempts at guessing is useful for password prompts. It is __absolutely crucial__ to TOTP prompts.
* How do you lock down a guesser? With TOTP it is easy: Just lock down the account they are guessing for. However, with passwords it is not easy: If you do that, I can just go to facebook or whatever, log in as 'ralscha', enter a random string for a password, do that a few times, and now YOU are locked out. A trivial denial-of-service attack. On the other hand, with TOTP, the story becomes: I enter 'ralscha', I __KNOW YOUR PASSWORD, APPARENTLY__, and _then_ I stumble at the TOTP roadblock. NOW locking down your account is entirely justified and the right avenue to stop guessing.

So, no unifying them.

You implement this in the GUI by switching it up once you get into 'extra security required' mode: [1] letting the entire screen be dedicated to it. If your authentication space is in a little box, you MUST break out of it. Looking different is GOOD here. [2] make it look different, the point is to make sure the user realizes this is not the normal flow anymore, [3] have 3 independent TOTP boxes for them to put a code into, clearly labelled, and [4] be a lot more forthcoming with feedback. If my phone is 24 minutes off the clock, and I enter my 3 codes, then the error I get should include the text 'your TOTP device's internal clock is 24 minutes ahead of the server's clock; TOTP requires that these 2 devices are within 2 minutes of each other. Please adjust your device's clock'.

**Comment by ralscha** [comment]
Thanks. This sounds very interesting. When I have some time I will try and implement this.

What would you recommend for applications that only have username and passwords or where TOTP is optional like in this example. 
What would you implement to prevent or to make it more difficult to brute force passwords?

**Comment by ralscha** [comment]
I wrote a new implementation based on your description:
https://github.com/ralscha/springsecuritytotp

It's online here:  https://demo.rasc.ch/totp/

**Comment by jazdw** [comment]
@rzwitserloot 
> I just keep guessing codes. Hey, any given time, 5 TOTP codes are valid, and there are only a million codes, so, any time I guess, I have a 1 in 200,000 shot of getting lucky. Assuming I can make a request every 100msec (and that's being 'generous'; usually I can go much faster; TOTP checking is not intentionally speed limited the way things like bcrypt are), I can fire off about 200k requests, giving me very reasonable odds I hit the jackpot in one of those, in less than 6 hours.

Can we actually do the math around this. You can make 300 guesses in 30s at a rate of 1/100ms. If 5 codes are valid at any given time then the probabilities are: 5 * 300 / 1000000 = 0.0015 or 0.15% for a given 30s window.

But we can't just add the probabilities together. From https://en.wikipedia.org/wiki/Bernoulli_trial it seems the formula to calculate this would be 
![image](https://user-images.githubusercontent.com/3579645/71770048-827f7100-2ee5-11ea-804c-8d299eade606.png)

So the chance of success after 720 attempts would be ([following the logic here](https://socratic.org/questions/how-do-you-find-the-probability-of-at-least-one-success-when-n-independent-berno)):
1 - (1- 0.0015)^720 = 0.66 or 66%

Did I work this out correctly? Would a solution be to simply only allow one TOTP code check every second?

**Comment by rzwitserloot** [comment]
Great, you used math to prove that where I oversimplified to '100%' chance
it is actually 66%. This obviously does not matter one iota; do you really
think a user will be satisfied? They tell you: "Wow, whoa, this security
issue that showed up on bugtraq says that my TOTP is completely useless and
all an attacker needs is my password to log in as me??" – and you answer
with: Don't worry about it, that's only 66% of the time; the remaining 33%,
well, let's assume they don't have more than 6 hours to try and it's
fiiine'??

I'm flabbergasted you'd even bothered to do this math. __ IT IS INSECURE __
how hard is this to follow?

No, allowing one TOTP a second doesn't fix anything.

But let's hypothetically go with 'sure, why not'. How do you track this?
Per IP? Bot nets have tons of IPs available, you can't do that. Per
account? Great, let's do that. This means you store some state someplace
(when is the last second that this TOTP code was tried and is it still that
second? If yes, wait 1 second before answering). If you're storing state
anyway, just store # of failed TOTPs. It is just as simple.

Let me put it another way: If I have a user's accountname AND password but
not their TOTP code, it should be possible for me to lock down their
account by trying random TOTP codes, and it should happen quickly. To undo
the lockdown, feel free to go with either an out-of-band security model
(you call them, send them an email, a postal letter, you know – the same
stuff your bank uses if you lose a card, or google uses if you lose your
email account's password), or ask for 3 consecutive codes. _ANYTHING ELSE_
is, by definition, in secure, because the amount of entropy in a TOTP code
is far too low to allow any form of guessing for any length of time.


 --Reinier Zwitserloot

**Comment by jazdw** [comment]
> Great, you used math to prove that where I oversimplified to '100%' chance
it is actually 66%. This obviously does not matter one iota; do you really
think a user will be satisfied? They tell you: "Wow, whoa, this security
issue that showed up on bugtraq says that my TOTP is completely useless and
all an attacker needs is my password to log in as me??" – and you answer
with: Don't worry about it, that's only 66% of the time; the remaining 33%,
well, let's assume they don't have more than 6 hours to try and it's
fiiine'??

> I'm flabbergasted you'd even bothered to do this math. __ IT IS INSECURE __
how hard is this to follow?

Jesus fucking christ dude, why are you getting so mad that someone questioned you? Security is all about examining risks which means that probabilities are heavily involved. If you aren't going to do the math correctly why bother?

Where did I ever say that 66% is acceptable?

**Comment by rzwitserloot** [comment]
It's your project, I tried to point out an obvious flaw, and I gave you the
industry standard solution to this flaw, and instead you are defending your
current implementation. I'm done with this; if you don't want to address
the issue, it's your funeral.

 --Reinier Zwitserloot

**Comment by jazdw** [comment]
Again you are putting words in my mouth. I do not have a current implementation and I am not defending anything. I am simply evaluating 2FA solutions and read this:

> And yet 6 hours later, I'm in their account. For sure. Guaranteed. If it's a nice server or it's hosting in a virtual park where I can trivially colocate right next to it in the network, maybe as little as half an hour.

Which did not seem right to me. Turns out it is categorically wrong.

You have also made several other unsubstantiated claims such as:
> Hey, any given time, 5 TOTP codes are valid
 
> the industry standard solution to this flaw

Not saying these are wrong, but given your attitude displayed in this thread please excuse me if I don't take your word for gospel.
