### ISSUE TITLE
not able to make push notifications pop up on screen of android phone

### ISSUE THREAD

**Issue by manuel-ch** [ralscha/blog2019#7]
see my post on SO: https://stackoverflow.com/questions/67862991/progressive-web-app-pwa-not-able-to-make-push-notifications-pop-up-on-screen-o

is this a known limitation of web push compared to native apps?

**Comment by ralscha** [comment]
Hi. Unfortunately I don't have any experience with this kind of push and mobile apps. I always wrap my apps for mobile with Cordova or Capacitor and then I use Firebase. Especially because iOS does not support PWA push notification.

**Comment by manuel-ch** [comment]
Hallo Ralph, vielen Dank für deine Antwort!

 

Könntest du sie in mein SO Post unter https://stackoverflow.com/questions/67862991/progressive-web-app-pwa-not-able-to-make-push-notifications-pop-up-on-screen-o ergänzen? Dieselbe Frage häuft sich inzwischen auf SO und mein Eindruck ist, dass Android mit Oreo eine ungewollte Einschränkung für PWA’s ergänzt hat…

 

Vielen Dank im Voraus

Manuel

 

Von: Ralph Schaer ***@***.***> 
Gesendet: Montag, 14. Juni 2021 15:21
An: ralscha/blog2019 ***@***.***>
Cc: manuel-ch ***@***.***>; Author ***@***.***>
Betreff: Re: [ralscha/blog2019] not able to make push notifications pop up on screen of android phone (#7)

 

Hi. Unfortunately I don't have any experience with this kind of push and mobile apps. I always wrap my apps for mobile with Cordova or Capacitor and then I use Firebase. Especially because iOS does not support PWA push notification.
